project:
  type: website
  output-dir: docs


website:
  title: "Noory Okthariza"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
      - href: data.qmd
        text: Data
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: flatly
    toc: false
    css: styles.css
    page-layout: article
    grid:
      body-width: 800px
    navbar:
      background: "#003366"   # dark blue, customize later
