project:
  type: website
  output-dir: docs


website:
  title: "Noory Okthariza"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
      - href: data.qmd
        text: Data
      - href: blog.qmd
        text: Blog
page-footer:
    left: |
      PhD Student in Political Science, University of Maryland  
      ğŸ“ College Park, MD  
      âœ‰ï¸ [noory@umd.edu](mailto:noory@umd.edu)  
      ğŸ“š [Google Scholar](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C21&q=noory+okthariza&btnG=&oq=noory+okth)  
      ğŸ†” [ORCID](https://orcid.org/0000-0001-8882-7763)  
      ğŸ’¼ [GitHub](https://github.com/noory-okthariza)

format: 
  html:
    theme: flatly
    toc: false
    css: styles.css
    page-layout: article
    grid:
      body-width: 800px
    navbar:
      background: "#003366"   # dark blue, customize later
